name: Reusable CI/CD Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      kubernetes_namespace:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Kubernetes
        uses: ./actions/helm-deploy
        with:
          namespace: ${{ inputs.kubernetes_namespace }}

